### PR TITLE
Migrate account-sdk-android to AndroidX

### LINKED ISSUE #470: AndroidX
Are there any plans to update this library to AndroidX?

`account-sdk-android` is the last library in our project that needs Jetifier:

> Cannot drop Jetifier due to following external dependencies:
> 
> * com.schibsted.account:account-sdk-android-pulse:2.0.0
> 
> * com.schibsted.account:account-sdk-android-ui:1.13.1
> 
> * com.schibsted.account:account-sdk-android-smartlock:1.13.1

Source: https://github.com/plnice/can-i-drop-jetifier

### PR DESCRIPTION
**Pull request by ziem**
I've migrated account-sdk-android to AndroidX. Unit and Android tests pass correctly. I also successfully logged in and registered a new account.

Screenshots:
Screenshot_1597404728

Closes #470

### CODE REVIEW

**Comment by ziem** [comment]
I've fixed it in 9ca0fea and now it is failing with this error:
>$ openssl aes-256-cbc -K $encrypted_de87219daf1c_key -iv $encrypted_de87219daf1c_iv -in deploy_key.enc -out deploy_key -d
>iv undefined
>
>The command "openssl aes-256-cbc -K $encrypted_de87219daf1c_key -iv $encrypted_de87219daf1c_iv -in deploy_key.enc -out deploy_key -d" failed and exited with 1 during .
>
>Your build has been stopped.

Do you have any idea what happened?

**Comment by zamzterz** [comment]
@ziem That's because of how the Travis file was structured before - [Travis doesn't allow PRs from forks to decrypt encrypted secrets](https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions). It should have been fixed by #473, so if you merge in latest master the tests should now work for this PR.

**Comment by ziem** [comment]
I pushed 838cbcd to my branch and also resolved a conflict (`.travis.yml` after you changes).

**Review by zamzterz — APPROVED** [review]

**Comment by zamzterz** [comment]
Looks great! Many thanks for sticking with it to the end 🙂

**Pull request merged**
